<a href="https://colab.research.google.com/github/melvindeepesh-boop/Loan-Default-Detection/blob/main/spam_email_classifier_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded= files.upload()

Saving spam email classifier .zip to spam email classifier .zip

In [6]:
import zipfile

with zipfile.ZipFile('spam email classifier .zip', 'r') as zip_ref:
    zip_ref.extractall()

In [7]:
import os

os.listdir()

['.config', 'emails.csv', 'spam email classifier .zip', 'sample_data']

In [9]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

In [10]:
import pandas as pd

df = pd.read_csv('emails.csv')

In [11]:
df.head()

  Email No.  the  to  ect  and  ...  military  allowing  ff  dry  Prediction
0   Email 1    0   0    1    0  ...         0         0   0    0           0
1   Email 2    8  13   24    6  ...         0         0   1    0           0
2   Email 3    0   0    1    0  ...         0         0   0    0           0
3   Email 4    0   5   22    0  ...         0         0   0    0           0
4   Email 5    7   6   17    1  ...         0         0   1    0           0

[5 rows x 3002 columns]

In [12]:
df.tail()

       Email No.  the  to  ect  and  ...  military  allowing  ff  dry  Prediction
5167  Email 5168    2   2    2    3  ...         0         0   0    0           0
5168  Email 5169   35  27   11    2  ...         0         0   1    0           0
5169  Email 5170    0   0    1    1  ...         0         0   0    0           1
5170  Email 5171    2   7    1    0  ...         0         0   1    0           1
5171  Email 5172   22  24    5    1  ...         0         0   0    0           0

[5 rows x 3002 columns]

In [13]:
df.shape

(5172, 3002)

In [14]:
df.columns

Index(['Email No.', 'the', 'to', 'ect', 'and', 'for', 'of', 'a', 'you', 'hou',
       ...
       'connevey', 'jay', 'valued', 'lay', 'infrastructure', 'military',
       'allowing', 'ff', 'dry', 'Prediction'],
      dtype='object', length=3002)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5172 entries, 0 to 5171
Columns: 3002 entries, Email No. to Prediction
dtypes: int64(3001), object(1)
memory usage: 118.5+ MB

In [16]:
df.describe()

               the           to  ...          dry   Prediction
count  5172.000000  5172.000000  ...  5172.000000  5172.000000
mean      6.640565     6.188128  ...     0.006961     0.290023
std      11.745009     9.534576  ...     0.098086     0.453817
min       0.000000     0.000000  ...     0.000000     0.000000
25%       0.000000     1.000000  ...     0.000000     0.000000
50%       3.000000     3.000000  ...     0.000000     0.000000
75%       8.000000     7.000000  ...     0.000000     1.000000
max     210.000000   132.000000  ...     4.000000     1.000000

[8 rows x 3001 columns]

In [17]:
df.isnull().sum()

Email No.     0
the           0
to            0
ect           0
and           0
             ..
military      0
allowing      0
ff            0
dry           0
Prediction    0
Length: 3002, dtype: int64

In [19]:
X = df.drop(['Email No.', 'Prediction'], axis=1)

y = df['Prediction']

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

In [21]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(4137, 3000)
(1035, 3000)
(4137,)
(1035,)

In [23]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()

model.fit(X_train, y_train)

MultinomialNB()

In [31]:
y_pred = model.predict(X_test)

In [33]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.9545893719806763